# Codecov configuration
# https://docs.codecov.com/docs/codecov-yaml

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 2%
    patch:
      default:
        target: auto
        threshold: 5%

ignore:
  # Test utilities - these are only used in tests and don't need coverage
  - "src/testutil.rs"
